default: &default
  log_level: debug

  aliases:
    - дядо
    # TODO: Fix this alias
    - дядо Коледа

  timezone: Europe/Sofia

test:
  <<: *default

  log_level: fatal
  aliases:

development:
  <<: *default

  log_level: debug

production:
  <<: *default

  log_level: debug
