default: &default
  log_level: debug

  aliases:
    - майсторе
    - баце

  lamps:
    Париж:
      - 5
    Коридора:
      - 6
      - 7
    Лондон:
      - 12
      - 13
    Лисабон:
      - 10
      - 11
    'Ню Йорк':
      - 22
      - 23
    Атина:
      - 8
      - 9
    Берлин:
      - 20
      - 21
    'Източен Берлин':
      - 20
    'Западен Берлин':
      - 21
    София:
      - 0
      - 1
      - 2
      - 3
      - 4
    Дубай:
      - 14
      - 15
    Банкок:
      - 13
      - 17
    Токио:
      - 18
      - 19
    Пекин:
      - 26
      - 27
    Москва:
      - 24
      - 25
    Терасата:
      - 28
      - 29
    Тоалетните:
      - 30
      - 31

test:
  <<: *default

  log_level: debug
  aliases:

development:
  <<: *default

  log_level: debug

production:
  <<: *default

  log_level: debug
