default: &default
  log_level: debug

  aliases:
    - дядо
    - дядо Коледа

test:
  <<: *default

  log_level: debug
  aliases:

development:
  <<: *default

  log_level: debug

production:
  <<: *default

  log_level: debug
