default: &default
  log_level: debug

  aliases:
    - майсторе
    - баце

  lamps:
    париж:
      - 5
    коридора:
      - 6
      - 7
    лондон:
      - 12
      - 13
    лисабон:
      - 10
      - 11
    'ню йорк':
      - 22
      - 23
    атина:
      - 8
      - 9
    берлин:
      - 20
      - 21
    'западен берлин':
      - 20
    'източен берлин':
      - 21
    софия:
      - 0
      - 1
      - 2
      - 3
      - 4
    'софия оберлихти':
      - 1
    'софия лунички':
      - 0
    'софия скрито':
      - 2
    'софия пред асансьора':
      - 3
    'софия пред берлин':
      - 4
    дубай:
      - 14
      - 15
    'западен дубай':
      - 14
    'източен дубай':
      - 15
    банкок:
      - 16
      - 17
    ':doynovski:':
      - 16
      - 17
    токио:
      - 18
      - 19
    пекин:
      - 26
      - 27
    москва:
      - 24
      - 25
    терасата:
      - 28
      - 29
    балкона:
      - 28
      - 29
    тоалетните:
      - 30
      - 31

test:
  <<: *default

  log_level: fatal
  aliases:

development:
  <<: *default

  log_level: debug

production:
  <<: *default

  log_level: debug
